### PR TITLE
Telegraf application for the rad1o badge

### PR DESCRIPTION
**Pull request by virtualabs**
We're proud to bring to you the Telegraf application for the rad1o badge ! It provides a morse transmitter able to send and receive messages through radio =). Plug your headset in and press the joystick to hear some cool sounds.

Enjoy !

### CODE REVIEW

**Comment by dl1com** [comment]
Just tested it with two rad1os, works fine for me.
Didn't verify the spectrum of the output, though.

**Comment by virtualabs** [comment]
We had hard times dealing with the low pass filter, but we checked the
signal with another badge and gqrx. The spectrum looks pretty good.

**Comment by Fensterbank** [comment]
Looks interesting. But unfortunately, this PR can not be automatically merged and cause work for @Sec42.
I recommend you to rebase your branch with the current upstream master to make it mergeable and raise the chance for an asap merge.

**Comment by virtualabs** [comment]
Done, seems the PR may be merged now. Tell me if something's wrong ;)

**Comment by virtualabs** [comment]
Okay, i'm going to fix all of this this evening (currently at Berlin Tegel
airport, trying to fix all of this with a different laptop ...).

I gonna check it all once at home and make a clean PR.

Btw, I'm fixing all this dirty code I made this night in order to avoid
warnings in the CI.

Damien

**Comment by virtualabs** [comment]
We're proud to bring to you the Telegraf application for the rad1o badge ! It provides a morse transmitter able to send and receive messages through radio =). Plug your headset in and press the joystick to hear some cool sounds.

Enjoy !

**Comment by virtualabs** [comment]
We're proud to bring to you the Telegraf application for the rad1o badge ! It provides a morse transmitter able to send and receive messages through radio =). Plug your headset in and press the joystick to hear some cool sounds.

Enjoy !

**Comment by virtualabs** [comment]
After some issues, seems the code is compiling fine against the upstream
master.

I cannot test it right now (no toolchain installed on this netbook), but it
should be ok. Anyone can test it again ?

**Comment by dl1com** [comment]
@virtualabs Just tested it, still works

**Comment by virtualabs** [comment]
That's great.

This is the last time I patch files and check how the compilation goes
through the CI ....

**Comment by skyschub** [comment]
I'd rather not see this getting merged in with a default of 2531 MHz. I'd rather set it to one of the ISM bands in europe, for example 149.9 MHz, 433.05 MHz, 868 MHz, ...

EDIT: I just realized the internal antenna is optimized to that frequency. Nevermind me.

**Comment by virtualabs** [comment]
I see, we chose this one because it was working great out-of-the-box with
the on-pcb antenna.

But I agree, it should be a standard ISM band. Should I modify it in order
to get it into the upstream master ?

Damien
Le 16 août 2015 14:54, "Dennis Schubert" notifications@github.com a
écrit :

**Comment by Sec42** [comment]
I'm sorry I didn't yet get to this. I'm trying to get the SDR stuff sanely into the campapp. I'll look into this afterwards.

**Comment by skyschub** [comment]
Well. Nah. Not being able to use the Telegraf without external antennas is bad. Anything between 2,400 GHz and 2,500 GHz is usable for ISM applications, the highest WiFi-channel (channel 14) is at 2484 MHz, so we should fine with using 2490 or something. Since you are only using some KHz bandwidth I guess we should be fine with, for example, specifing 10 Channels and letting the users set those instead of the raw frequency?

@Sec42 Sure, no worries. You're doing great work.

**Comment by virtualabs** [comment]
Basically, the user can tune the frequency with the joystick (up/down at
this moment, I'm thinking of using left/right instead).

The Telegraf can be by default tuned to 2490MHz, and any user is free to
tune it to 2495 or something else very easily.

And of course, anybody with an external antenna should be able to tune it
to 868MHz or 433MHz. I may need to implement some kinda fast-forward
selection for the user interface, I guess.
Le 16 août 2015 18:04, "Dennis Schubert" notifications@github.com a
écrit :

**Pull request merged**
