### PR TITLE
HackRF UI

### PR DESCRIPTION
**Pull request by schneider42**
Looks like this:

sam_1920
sam_1921

### CODE REVIEW

**Comment by ralphtheninja** [comment]
:100:

**Comment by dos1** [comment]
I love it!

**Comment by schneider42** [comment]
@Sec42: I think we have to alter the build system a bit to make this rally work.

After compiling for hackrf, the object files are not rebuild with `-DHACKRF_ENABLE_UI=1` which causes this app to not show any data.

**Comment by schneider42** [comment]
@Sec42: Solved it another way using weak definitions

**Pull request merged**
